title: Clash Royale api 
description: "August 2023 to June 2024"
owner_name: Ashwin V
github_username: Ashwinv93
github_repo: "Nighthawk-Pages"
baseurl: "/GLADV2Frontend"
remote_theme: jekyll/minima
minima:
  social_links:
    - { platform: github, user_url: "https://github.com/jplip"}
    - { platform: github, user_url: "https://github.com/iKAN2025"}
    - { platform: github, user_url: "https://github.com/vibha-yganji"}
    - { platform: github, user_url: "https://github.com/flying-book"}
# remote_theme: pages-themes/dinky@v0.2.0
# remote_theme: pages-themes/minimal@v0.2.0
# remote_theme: pages-themes/hacker@v0.2.0
# remote_theme: pages-themes/cayman@v0.2.0
# remote_theme: pages-themes/time-machine@v0.2.0
plugins:
- jekyll-remote-theme
future: true
